theme: jekyll-theme-slate

title: [Project Vision]
description: [Capstone Project for Extensive Vision AI Program]

show_downloads: ["true"]

github:
  zip_url: https://github.com/vigneshbabupj/Project_Vision/archive/main.zip
  tar_url: https://github.com/vigneshbabupj/Project_Vision/archive/main.zip
  repository_url: https://github.com/vigneshbabupj/Project_Vision.git
